name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check num_episodes
      id: check-num_episodes
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Check num_episodes
        setup-command: ''
        command: cat config.yaml | grep 'num_episodes:'
        input: ''
        expected-output: '7'
        comparison-method: contains
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-NUM_EPISODES_RESULTS: "${{steps.check-num_episodes.outputs.result}}"
      with:
        runners: check-num_episodes
